### PR TITLE
Make it work with go get

### PR DESCRIPTION
**Pull request by Fale**

### CODE REVIEW

**Comment by Fale** [comment]
This would fix #1

**Comment by Fale** [comment]
The CI broken, but I think this is because it has no idea how to compile it, while it works when runned with "go get"

**Comment by danapsimer** [comment]
Sorry it took me so long to merge this.  Thanks for the contribution.  I was thinking this needed to be done too but had not gotten around to it.

**Comment by Fale** [comment]
Hi,
Thanks for the merge,

It seems like there are multiple references to my repo instead of yours.
You can probably grep for 'fale' in the sources and replace those.

**Comment by danapsimer** [comment]
Actually the original is on bitbucket: https://bitbucket.org/rickb777/drupal2hugo

**Comment by Fale** [comment]
On Wed, Aug 17, 2016 at 08:30:15AM -0700, danapsimer wrote:

> Actually the original is on bitbucket: https://bitbucket.org/rickb777/drupal2hugo

I think that one is dead...

**Pull request merged**
